services:
  app:
    build: .
    container_name: sqoush-app
    ports:
      - "8080:8080"
    environment:
      - APP=prod
      - DB_PATH=/data/sqoush.db
      - DB_MIGRATIONS_DIR=/app/migrations
    volumes:
      - sqoush-data:/data

volumes:
  sqoush-data:
